### ISSUE TITLE
Ultimul link din alte resurse este nefuncțional

### ISSUE THREAD

**Issue by JusticeBringer** [palcu/fmi#43]
La readme.md pentru repozitoriul FMI, ultimul link din secțiunea ”Alte resurse” întoarce eroarea 404.

Link-ul este următorul:
https://drive.google.com/folderview?id=0B0-Ney8GB2GyS2hRcFRQRFpxdlU&u

**Comment by palcu** [comment]
https://github.com/palcu/fmi/commit/71086fd9516f3097376c9f4dbb7b385c856b8b7c

Dat fiind că n-am documentat ce era linkul și de unde îl aveam, o să îl șterg.

Mulțam.
