### ISSUE TITLE
Link gresit pe readme de IA

### ISSUE THREAD

**Issue by JusticeBringer** [palcu/fmi#53]
Pe linkul de [readme IA]( https://github.com/palcu/fmi/blob/master/ia.md), este urmatoarea sectiune:

Reprezentarea Cunoștințelor - Florentina Hristea
Teorie
Un rezumat( teorie + bucatele de cod de la laborator) se gaseste online aici cu sursa aici.

**_Seminarul se gaseste online aici_ cu sursa aici. Sunt explicate bazele Prolog si sunt facute cateva exercitii.**

Din nefericice, seminarul are link catre https://www.vladionescu.me/seminar.html, dar face redirect catre https://www.vladionescu.me/index.html.

Daca nu mai exista link-ul, ar trebui sters.

**Comment by palcu** [comment]
@Vlaaaaaaad vezi că ai stricat niște linkuri. Și nu le găsesc nici în Wayback Machine.

http://web.archive.org/web/*/https://www.vladionescu.me/seminar.html

**Comment by Vlaaaaaaad** [comment]
Yup, wiped that from the universe. Foloseam Stackedit si alea erau export-uri de MD in HTML care inceapeau dea sa nu mai mearga.

Sursele pentru fisierele alea sunt in [https://github.com/Vlaaaaaaad/FMI-public-materials](https://github.com/Vlaaaaaaad/FMI-public-materials), Seminarul de IA fiind la [InteligentaArtificiala/seminar.md](https://github.com/Vlaaaaaaad/FMI-public-materials/blob/master/InteligentaArtificiala/seminar.md).

**Comment by palcu** [comment]
Mulțam fain, l-am adăugat. https://github.com/palcu/fmi/commit/033d50b979ddae6bdfa9d49fd32def6b1131357e
