### ISSUE TITLE
Link neexistent pe pagina de pao.md

### ISSUE THREAD

**Issue by JusticeBringer** [palcu/fmi#56]
Pe readme-ul de pao.md link-ul "Cursuri 2017" nu exista.

**Comment by palcu** [comment]
Nu știu exact cine l-a adăugat pentru că [commitul](https://github.com/palcu/fmi/commit/a36102925dd35d48c7f3840c4f3c02c13794c548) nu e legat de un cont de Github. Am șters linkul.
