### ISSUE TITLE
ASD?

### ISSUE THREAD

**Issue by justinianpopa** [palcu/fmi#9]
Ceva materiale/informații pentru Algoritmi și Structuri de date? Pare ca este singura materie de la informatica la care lipsesc orice fel de informații concrete pe internet.

**Comment by palcu** [comment]
Sincer, m-am prezentat direct la examenul ăla, am cunoscut-o pe profa de la curs și l-am luat. Se trage de la olimpiadele din liceu. Dacă tu găsești ceva pe grupuri, simte-te comod să completezi lista, dar eu n-am avut nevoie.

**Comment by justinianpopa** [comment]
Sunt ceva materiale pe moodle dar nu stiu daca e voie sa le pun aici.... ?

**Comment by palcu** [comment]
Pe alea oricum le are toată lumea. Poți pune un link la ele
